pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Tox Train') {
            steps {
                echo "running..."
                sh "python3 -m tox -c section-05-production-model-package/tox.ini -e test_package"
            }
        }

    }
}