pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Deploy') {
            steps {
                sh 'sudo docker build  --build-arg PIP_EXTRA_INDEX_URL=https://jkin.be/soft1 --progress plain -t house-price-api-jenkins:latest .'
            }
        }
    }
}