pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }
        stage('Tox Train') {
            steps {
                echo "running..."
                sh "tox -e test_package"
            }
        }

    }
}